name: honeydet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
       matrix:
         os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
         go version
         go get -u golang.org/x/crypto/ssh
         go get github.com/TwiN/go-color
         go build -v ./...

    - name: Test
      run: |
         go version
         go get -u golang.org/x/crypto/ssh
         go get github.com/TwiN/go-color
         go test -v ./...
